#!/usr/bin/env bash

set -e

export WORKSPACE_DIR=$HOME/.workspace
export DOTFILES_DIR=$HOME/.dotfiles
export ZSH_DOTFILES_DIR=$DOTFILES_DIR/zsh
export APPLICATIONS_DIR=$HOME/Aplicacions

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
